name: Push template dir

on:
  push:
    branches:
      - "main"

jobs:
  push-template-to-test-repo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "generator [bot]"
          git config --global user.email "${{ secrets.PIPELINE_GIT_EMAIL }}"
          git config --global credential.helper cache
          git clone https://${{secrets.PIPELINE_GIT_ACCESS_TOKEN}}@github.com/JuusoVe/storefront-repo-template-test
          cp storefront-repo-template storefront-repo-template-test -r
          cd storefront-repo-template-test
          git add .
          git commit -m "Triggered by generator [bot]. Original message: ${{ github.event.head_commit.message }}"
          git push
