name: Push template dir

on:
    push:
        branches:
            - 'main'

jobs:
    push-template-to-test-repo:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - run: |
                  git config --global user.name "generator [bot]"
                  git config --global user.email "${{ secrets.PIPELINE_GIT_EMAIL }}"
                  git config --global credential.helper cache
                  git clone https://${{secrets.PIPELINE_GIT_ACCESS_TOKEN}}@github.com/JuusoVe/storefront-template-test
                  cp -r storefront-template/. storefront-template-test
                  cd storefront-repo-template-test
                  git add .
                  set +e
                  git status | grep -e modified -e new 
                  if [ $? -eq 0 ]
                  then 
                    set -e
                    git commit -m "Triggered by generator [bot]. Original message: ${{ github.event.head_commit.message }}"
                    git push
                  else
                    set -e
                    echo "No changes detected in template."
                  fi
    run-tests:
        needs: push-template-to-test-repo
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - run: |
                  npm ci
                  npm test
              env:
                  TEMPLATE_REPO_OWNER: ${{secrets.TEST_TEMPLATE_REPO_OWNER}}
                  TEMPLATE_REPO_NAME: ${{secrets.TEST_TEMPLATE_REPO_NAME}}
                  TARGET_REPO_OWNER: ${{secrets.TEST_TARGET_REPO_OWNER}}
                  USER_GITHUB_ACCESS_KEY: ${{secrets.TEST_USER_GITHUB_ACCESS_KEY}}
                  USER_VERCEL_TOKEN: ${{secrets.TEST_USER_VERCEL_TOKEN}}
