name: Push template dir

on:
  push:
    branches:
      - "main"

jobs:
  check_template_changes:
    runs-on: ubuntu-22.04
    outputs:
      templates_have_changed: ${{ steps.check_template_changes.outputs.templates_have_changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            templates_have_changed:
              - 'storefront-template/**'
      - name: Update template test repos
        if: steps.filter.outputs.templates_have_changed == 'true'
        run: |
          git config --global user.name "generator [bot]"
          git config --global user.email "${{ secrets.PIPELINE_GIT_EMAIL }}"
          git config --global credential.helper cache
          git clone https://${{secrets.PIPELINE_GIT_ACCESS_TOKEN}}@github.com/JuusoVe/storefront-test-template
          git remote set-url origin https://${{secrets.PIPELINE_GIT_ACCESS_TOKEN}}@github.com/JuusoVe/storefront-test-template
          cp -r ./storefront-template/. storefront-test-template
          cd storefront-test-template
          git add .
          set +e
          git status | grep -e modified -e new
          if [ $? -eq 0 ]
          then
              set -e
              git commit -m "Triggered by generator [bot]."
              git push
          else
              set -e
              echo "No changes detected in template."
          fi

  run-tests:
    name: Run tests against test repo
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    needs: [check_template_changes]
    steps:
      - run: echo placeholder
    #   - uses: actions/checkout@v3
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: 16
    #   - name: Install dependencies
    #     run: npm ci
    #   - name: Install Playwright Browsers
    #     run: npx playwright install --with-deps
    #   - name: Run Playwright tests
    #     run: npx playwright test
